#!/usr/bin/env bash

# Tool for disassembling shellcode string
#
# Author: Oleg Mitrofanov (reider-roque) 2015

printf "$1" | ndisasm -b32 -

# Old inefficient way =)
#
# tmpfile=$(mktemp)
# printf "$1" > "$tmpfile"
# ndisasm -b32 "$tmpfile"
# rm -rf "$tmpfile" 
#
