#!/bin/bash

# Tool for dumping shellcode string from instructions of the
# .text (code) section of the given binary 
# Author: Oleg Mitrofanov (reider-roque) 2015

shellcode=$(
    objdump -d "$1" |   # Dump the .text (code) section 
    grep '[0-9a-f]:' |  # Select only lines with memory addresses 
    cut -d$'\t' -f2 |   # Get the column with opcodes
    grep -v 'file' |    # Eliminate file format string for binaries with 
                        # names consisting of 0-9a-f chars
    tr -d " \n" |       # Remove all spaces and newline chars
    sed 's/../\\x&/g'   # Insert \x in front of every 2 chars
)

echo "Length:  $(printf $shellcode | wc -c)"
echo "Payload: \"$shellcode\""
