#!/usr/bin/env python

# Tool for converting string to instructions for pushing them to stack
#
# Author: Oleg Mitrofanov (reider-roque) 2015

import binascii
import os.path as op
import sys

if len(sys.argv) != 2:
    script_name = op.basename(__file__)
    print("Error: too much arguments")
    print("Usage: {} STRING".format(script_name))
    sys.exit(1)

strvar = sys.argv[1]
if len(strvar) % 4 != 0:
    print("Error: string length must be a multiple of 4. Find a way to align it.")
    print("String length: {}".format(len(strvar)))
    sys.exit(1)

strvar = strvar[::-1]   # reverse string
# divide string onto 4-letter chunks
strchunks = [strvar[i:i+4] for i in range(0, len(strvar), 4)] 
for chunk in strchunks:
    chunk = binascii.hexlify(chunk.encode()) # convert letters to byte codes
    print("push 0x{}".format(chunk.decode('utf-8')))
